// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/create_event": {
            "post": {
                "description": "Creates an event for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Create a new event",
                "parameters": [
                    {
                        "description": "Event data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateRequestV1"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.CreateResponseV1"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/api/v1/delete_event": {
            "post": {
                "description": "Deletes an event for a user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Delete an event",
                "parameters": [
                    {
                        "description": "Event delete data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteRequestV1"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteResponseV1"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/api/v1/events_for_day": {
            "get": {
                "description": "Returns all events for a given day for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get events for a day",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ListOfEventsResponseV1"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/api/v1/events_for_month": {
            "get": {
                "description": "Returns all events for a given month for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get events for a month",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ListOfEventsResponseV1"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/api/v1/events_for_week": {
            "get": {
                "description": "Returns all events for a given week for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get events for a week",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date in YYYY-MM-DD format",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ListOfEventsResponseV1"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse500"
                        }
                    }
                }
            }
        },
        "/api/v1/update_event": {
            "post": {
                "description": "Updates an event's text or date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Update an existing event",
                "parameters": [
                    {
                        "description": "Event update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateRequestV1"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateResponseV1"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse400"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse500"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.CreateRequestV1": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "EventDate is the date of the event in YYYY-MM-DD format.",
                    "type": "string",
                    "example": "2028-12-04"
                },
                "text": {
                    "description": "Text is the optional description of the event.",
                    "type": "string",
                    "example": "Touch grass"
                },
                "user_id": {
                    "description": "UserID is the ID of the user who owns the event.",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "v1.CreateResponseV1": {
            "type": "object",
            "properties": {
                "event_id": {
                    "description": "EventID is the unique identifier of the newly created event.",
                    "type": "string",
                    "example": "3383503d-fb71-4b8c-85bd-a914c84252a9"
                }
            }
        },
        "v1.DeleteRequestV1": {
            "type": "object",
            "required": [
                "event_id",
                "user_id"
            ],
            "properties": {
                "event_id": {
                    "description": "EventID is the unique identifier of the event to delete.",
                    "type": "string",
                    "example": "3383503d-fb71-4b8c-85bd-a914c84252a9"
                },
                "user_id": {
                    "description": "UserID is the ID of the user who owns the event.",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "v1.DeleteResponseV1": {
            "type": "object",
            "properties": {
                "event_deleted": {
                    "description": "Deleted indicates whether the event was successfully deleted.",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "v1.ErrorResponse400": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code is the HTTP status code.",
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "description": "Message is a human-readable description of the error.",
                    "type": "string",
                    "example": "invalid date format, expected YYYY-MM-DD"
                }
            }
        },
        "v1.ErrorResponse500": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code is the HTTP status code.",
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "description": "Message is a human-readable description of the error.",
                    "type": "string",
                    "example": "internal server error"
                }
            }
        },
        "v1.EventDtoV1": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "EventDate is the date of the event in YYYY-MM-DD format.",
                    "type": "string",
                    "example": "2028-12-04"
                },
                "event_id": {
                    "description": "EventID is the unique identifier of the event.",
                    "type": "string",
                    "example": "3383503d-fb71-4b8c-85bd-a914c84252a9"
                },
                "text": {
                    "description": "Text is the description of the event.",
                    "type": "string",
                    "example": "Touch grass"
                }
            }
        },
        "v1.ListOfEventsResponseV1": {
            "type": "object",
            "properties": {
                "events": {
                    "description": "Events is the list of events returned by the API.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.EventDtoV1"
                    }
                }
            }
        },
        "v1.UpdateRequestV1": {
            "type": "object",
            "properties": {
                "event_id": {
                    "description": "EventID is the unique identifier of the event to update.",
                    "type": "string",
                    "example": "3383503d-fb71-4b8c-85bd-a914c84252a9"
                },
                "new_date": {
                    "description": "NewDate is the new optional date for the event in YYYY-MM-DD format.",
                    "type": "string",
                    "example": "2028-12-05"
                },
                "text": {
                    "description": "Text is the new optional description for the event.",
                    "type": "string",
                    "example": "Grind leetcode"
                },
                "user_id": {
                    "description": "UserID is the ID of the user who owns the event.",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "v1.UpdateResponseV1": {
            "type": "object",
            "properties": {
                "event_updated": {
                    "description": "Updated indicates whether the event was successfully updated.",
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
